@startuml
title Educator Batch Compilation and Feedback Platform - Structure

package "Main Application" {
    class main.py
}

package "src" {
    
    package "controllers" {
        class buttons_controller.py
        class batch_controller.py
        class batch_worker.py
        class asm_controller.py
        class asm_worker.py
        class int_controller.py
        class int_worker.py
    }

    package "services" {
        class batch_service.py
        class asm_service.py
        class int_service.py
    }

    package "views" {
        class buttons.py
        class buttons_functions.py
        class file_loader.py
        class main_windows.py
        class show_stats.py
    }

    package "logic" {
        class cpp_execturor.py
        class intermidiate_execturor.py
        class assembly_execturor.py
        class compiler.py
        class submit_files.py
    }
}

main.py --> buttons_controller.py
buttons_controller.py --> batch_worker.py
buttons_controller.py --> asm_worker.py
buttons_controller.py --> int_worker.py

batch_worker.py --> batch_controller.py
batch_controller.py --> batch_service.py

asm_worker.py --> asm_controller.py
asm_controller.py --> asm_service.py

int_worker.py --> int_controller.py
int_controller.py --> int_service.py

buttons_controller.py --> buttons.py
buttons.py --> buttons_functions.py
buttons.py --> file_loader.py
buttons.py --> main_windows.py
buttons_controller.py --> show_stats.py

intermidiate_execturor.py --> cpp_execturor.py
compiler.py --> intermidiate_execturor.py
compiler.py --> assembly_execturor.py
submit_files.py --> compiler.py

@enduml
